import React from 'react'

export const metadata = {
    title: 'Acerca de',
    description: 'Generated by Next.js',
}

const about = () => {
    return (
        <div><h1>acera de la homosexualidad</h1></div>
    )
}

export default about