import Navbar from "@/components/Navbar"
import "./globals.css"
import {
  Roboto
} from "next/font/google"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  weight: ["300", "400"],
  styles: ["italic", "normal"],
  subsets: ["latin"]
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
